# ============================================
# GitHub Actions Workflow: CI - My First Workflow
# ============================================

# The name of the workflow shown in the GitHub Actions UI
name: My First Workflow

# --------------------------------------------
# Workflow Trigger Configuration
# --------------------------------------------

# The `on` block defines the events that trigger the workflow.
on:
  # Trigger when code is pushed to the "main" branch
  push:
    branches: [ "main" ]

  # Trigger when a pull request targets the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allow manually triggering this workflow from the GitHub Actions UI
  workflow_dispatch:

# --------------------------------------------
# Workflow Jobs Section
# --------------------------------------------

# `jobs` defines a map of job names and their configurations
jobs:
  first_job:
    # Specify the type of virtual machine to run the job
    runs-on: ubuntu-latest

    # Each job contains a sequence of steps to run
    steps:
      # Step 1: Check out the source code from the repository
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      # Step 2: Run a basic script that prints a message, lists directory contents, and displays README.MD
      - name: List and Read file
        run: |
          echo "My first GitHub Actions Job"
          ls -ltra
          cat README.MD

      # Step 3: Generate ASCII art using the 'cowsay' utility and write it to dragon.txt
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
