name: Generate ASCII Artwork

on:

  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2
      
      - name: Executing Shell Script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
      
