name: Generate ASCII Artwork-2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      
      - name: Execute Cowsay Program
        run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt
      
      - name: Sleep for 30 seconds
        run: sleep 30
      
  test_job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Test File Exist
        run: grep -i "dragon" dragon.txt


  deploy_job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying