name: Exploring Variables and Secrets

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker build -t docker.io/dockerUsername/imageName:latest


      - name: Docker Login
        run: docker login --username=dockerUsername --password=


      
